# Generated by Django 2.0.7 on 2018-08-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokk', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
    ]
