# Generated by Django 2.0.7 on 2018-08-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokk', '0003_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='artdesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.IntegerField(default=0)),
                ('b_name', models.CharField(max_length=15)),
                ('b_auth', models.CharField(max_length=15)),
                ('b_review', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.IntegerField(default=0)),
                ('b_name', models.CharField(max_length=15)),
                ('b_auth', models.CharField(max_length=15)),
                ('b_review', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='poetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.IntegerField(default=0)),
                ('b_name', models.CharField(max_length=15)),
                ('b_auth', models.CharField(max_length=15)),
                ('b_review', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='political',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.IntegerField(default=0)),
                ('b_name', models.CharField(max_length=15)),
                ('b_auth', models.CharField(max_length=15)),
                ('b_review', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='programing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.IntegerField(default=0)),
                ('b_name', models.CharField(max_length=15)),
                ('b_auth', models.CharField(max_length=15)),
                ('b_review', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
