# Generated by Django 2.0.7 on 2018-08-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokk', '0004_auto_20180811_0015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
