# Generated by Django 2.0.7 on 2018-08-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokk', '0006_auto_20180811_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='political',
            name='b_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
