# Generated by Django 2.0.7 on 2018-08-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bokk', '0007_political_b_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artdesign',
            name='b_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='children',
            name='b_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='poetry',
            name='b_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='programing',
            name='b_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
